package StringConcatModule;


/**
* StringConcatModule/_StringConcatStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcatModule.idl
* Tuesday, 30 May, 2023 1:50:16 AM IST
*/

public class _StringConcatStub extends org.omg.CORBA.portable.ObjectImpl implements StringConcatModule.StringConcat
{

  public String concatenate_strings (String str1, String str2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("concatenate_strings", true);
                $out.write_string (str1);
                $out.write_string (str2);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return concatenate_strings (str1, str2        );
            } finally {
                _releaseReply ($in);
            }
  } // concatenate_strings

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:StringConcatModule/StringConcat:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _StringConcatStub
