package StringConcatModule;


/**
* StringConcatModule/StringConcatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcatModule.idl
* Tuesday, 30 May, 2023 1:50:16 AM IST
*/

public interface StringConcatOperations 
{
  String concatenate_strings (String str1, String str2);
} // interface StringConcatOperations
