package StringConcatModule;


/**
* StringConcatModule/StringConcat.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcatModule.idl
* Tuesday, 30 May, 2023 1:50:16 AM IST
*/

public interface StringConcat extends StringConcatOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface StringConcat
