package StringConcatModule;

/**
* StringConcatModule/StringConcatHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from StringConcatModule.idl
* Tuesday, 30 May, 2023 1:50:16 AM IST
*/

public final class StringConcatHolder implements org.omg.CORBA.portable.Streamable
{
  public StringConcatModule.StringConcat value = null;

  public StringConcatHolder ()
  {
  }

  public StringConcatHolder (StringConcatModule.StringConcat initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = StringConcatModule.StringConcatHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    StringConcatModule.StringConcatHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return StringConcatModule.StringConcatHelper.type ();
  }

}
